Hello microverse
Bhekisile/Hello-Microverse1 pull request #1
Opened 2022-11-29 21:57 UTC by Bhekisile

2022-11-29 23:35 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: 
Hi @Bhekisile, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif">

## Highlights
-  Linters are passing :+1: 
- Good commit messages :+1: 
- `node_modules` and `test.md` are present in `.gitignore` :clap: :clap: 

## Required Changes ♻️

- Kindly submit this same pull request for future reviews it's not recommended to change branches or repositories for next reviews.
- I think It would be better if you added a nice title and summary to your Pull request, to make it look more professional.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 23:35 UTC, GedeonTS commented on README.md
> +Ensuring no linter errors
- [ ] I think it would be better if you use the template provided by microverse, in order to make it look more professional. Please find the link [here](https://github.com/microverseinc/readme-template)

2022-11-29 23:35 UTC, GedeonTS commented on index.html
> +    <link rel="sheetstyles" href="styles.css">
- [ ] Kindly make sure the css file is well linked to the html, Iet's use `rel="stylesheet"` instead of `rel="sheetstyles"`.

2022-11-30 11:23 UTC, Bhekisile commented on README.md
> +Ensuring no linter errors
Rectified, thank you for your feedback.

2022-11-30 11:24 UTC, Bhekisile commented on index.html
> +    <link rel="sheetstyles" href="styles.css">
Rectified, thank you for your feedback.

2022-11-30 12:58 UTC, closed without merging